name: "solved-box"
author: BieNew22
description: "Update your Solved.ac stats"
branding:
  icon: code
  color: blue
runs:
  runs-on: ubuntu-latest
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run
      run: python src/main.py